name: first workflow
on: workflow_dispatch 
jobs:
  first_job:
  runs_on: ubuntu_latest
  steps:
    -name: Print Kr Bhai
    run: echo "Hello CI/CD"
    -name: Print End Kr Bhai
    run: echo "Khatam tata Bye Bye"
